/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace thriftGrafo
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Aresta : TBase
  {
    private int _verticeInicio;
    private int _verticeFim;
    private bool _FlagBidirecional;
    private double _peso;
    private string _descricao;

    public int VerticeInicio
    {
      get
      {
        return _verticeInicio;
      }
      set
      {
        __isset.verticeInicio = true;
        this._verticeInicio = value;
      }
    }

    public int VerticeFim
    {
      get
      {
        return _verticeFim;
      }
      set
      {
        __isset.verticeFim = true;
        this._verticeFim = value;
      }
    }

    public bool FlagBidirecional
    {
      get
      {
        return _FlagBidirecional;
      }
      set
      {
        __isset.FlagBidirecional = true;
        this._FlagBidirecional = value;
      }
    }

    public double Peso
    {
      get
      {
        return _peso;
      }
      set
      {
        __isset.peso = true;
        this._peso = value;
      }
    }

    public string Descricao
    {
      get
      {
        return _descricao;
      }
      set
      {
        __isset.descricao = true;
        this._descricao = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool verticeInicio;
      public bool verticeFim;
      public bool FlagBidirecional;
      public bool peso;
      public bool descricao;
    }

    public Aresta() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                VerticeInicio = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                VerticeFim = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Bool) {
                FlagBidirecional = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.Double) {
                Peso = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.String) {
                Descricao = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("Aresta");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.verticeInicio) {
          field.Name = "verticeInicio";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(VerticeInicio);
          oprot.WriteFieldEnd();
        }
        if (__isset.verticeFim) {
          field.Name = "verticeFim";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(VerticeFim);
          oprot.WriteFieldEnd();
        }
        if (__isset.FlagBidirecional) {
          field.Name = "FlagBidirecional";
          field.Type = TType.Bool;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(FlagBidirecional);
          oprot.WriteFieldEnd();
        }
        if (__isset.peso) {
          field.Name = "peso";
          field.Type = TType.Double;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(Peso);
          oprot.WriteFieldEnd();
        }
        if (Descricao != null && __isset.descricao) {
          field.Name = "descricao";
          field.Type = TType.String;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Descricao);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Aresta(");
      bool __first = true;
      if (__isset.verticeInicio) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("VerticeInicio: ");
        __sb.Append(VerticeInicio);
      }
      if (__isset.verticeFim) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("VerticeFim: ");
        __sb.Append(VerticeFim);
      }
      if (__isset.FlagBidirecional) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("FlagBidirecional: ");
        __sb.Append(FlagBidirecional);
      }
      if (__isset.peso) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Peso: ");
        __sb.Append(Peso);
      }
      if (Descricao != null && __isset.descricao) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Descricao: ");
        __sb.Append(Descricao);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
