/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace thriftGrafo
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class GrafoAtributo : TBase
  {
    private List<Vertice> _vertices;
    private List<Aresta> _arestas;

    public List<Vertice> Vertices
    {
      get
      {
        return _vertices;
      }
      set
      {
        __isset.vertices = true;
        this._vertices = value;
      }
    }

    public List<Aresta> Arestas
    {
      get
      {
        return _arestas;
      }
      set
      {
        __isset.arestas = true;
        this._arestas = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool vertices;
      public bool arestas;
    }

    public GrafoAtributo() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List) {
                {
                  Vertices = new List<Vertice>();
                  TList _list0 = iprot.ReadListBegin();
                  for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                  {
                    Vertice _elem2;
                    _elem2 = new Vertice();
                    _elem2.Read(iprot);
                    Vertices.Add(_elem2);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.List) {
                {
                  Arestas = new List<Aresta>();
                  TList _list3 = iprot.ReadListBegin();
                  for( int _i4 = 0; _i4 < _list3.Count; ++_i4)
                  {
                    Aresta _elem5;
                    _elem5 = new Aresta();
                    _elem5.Read(iprot);
                    Arestas.Add(_elem5);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("GrafoAtributo");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Vertices != null && __isset.vertices) {
          field.Name = "vertices";
          field.Type = TType.List;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, Vertices.Count));
            foreach (Vertice _iter6 in Vertices)
            {
              _iter6.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (Arestas != null && __isset.arestas) {
          field.Name = "arestas";
          field.Type = TType.List;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, Arestas.Count));
            foreach (Aresta _iter7 in Arestas)
            {
              _iter7.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("GrafoAtributo(");
      bool __first = true;
      if (Vertices != null && __isset.vertices) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Vertices: ");
        __sb.Append(Vertices);
      }
      if (Arestas != null && __isset.arestas) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Arestas: ");
        __sb.Append(Arestas);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
